/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author aleja
 */
public class VentanaGanador extends javax.swing.JDialog {
    private String usuario;
    
    public VentanaGanador(java.awt.Frame parent, boolean modal,String usuario) {
        super(parent, modal);
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaUsuario = new javax.swing.JLabel();
        etiquetaGanaste = new javax.swing.JLabel();
        juegoDeNuevo = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        etiquetaImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        etiquetaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaUsuario.setText("Felicitaciones "+usuario);

        getContentPane().add(etiquetaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, -1));

        etiquetaGanaste.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        etiquetaGanaste.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaGanaste.setText("Ganaste!!!");
        getContentPane().add(etiquetaGanaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        juegoDeNuevo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        juegoDeNuevo.setText("Jugar de nuevo");
        juegoDeNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoDeNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(juegoDeNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        salir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        etiquetaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ganador.gif"))); // NOI18N
        getContentPane().add(etiquetaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void juegoDeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoDeNuevoActionPerformed
        dispose();        
    }//GEN-LAST:event_juegoDeNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaGanador dialog = new VentanaGanador(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaGanaste;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JButton juegoDeNuevo;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
